### ISSUE TITLE
No route matches [GET] "/apple-touch-icon-120x120-precomposed.png"

### ISSUE THREAD

**Issue by SpringMT** [SpringMT/rack-favicon_all#2]
```
/apple-touch-icon-120x120-precomposed.png
```

が抜けている

**Comment by Amandeepsinghghai** [comment]
@SpringMT Were you able to find the root cause of this issue?

**Comment by SpringMT** [comment]
YES
Fix https://github.com/SpringMT/rack-favicon_all/pull/3

**Comment by SpringMT** [comment]
Released 
https://rubygems.org/gems/rack-favicon_all/versions/0.0.4
